// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: controller/pb/model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeadReplyStatusT int32

const (
	HeadReply_OK             HeadReplyStatusT = 0
	HeadReply_NOT_FOUND      HeadReplyStatusT = 1
	HeadReply_INTERNAL_ERROR HeadReplyStatusT = 2
)

// Enum value maps for HeadReplyStatusT.
var (
	HeadReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "INTERNAL_ERROR",
	}
	HeadReplyStatusT_value = map[string]int32{
		"OK":             0,
		"NOT_FOUND":      1,
		"INTERNAL_ERROR": 2,
	}
)

func (x HeadReplyStatusT) Enum() *HeadReplyStatusT {
	p := new(HeadReplyStatusT)
	*p = x
	return p
}

func (x HeadReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeadReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[0].Descriptor()
}

func (HeadReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[0]
}

func (x HeadReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeadReplyStatusT.Descriptor instead.
func (HeadReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{1, 0}
}

type CreateListReplyStatusT int32

const (
	CreateListReply_OK             CreateListReplyStatusT = 0
	CreateListReply_DUPLICATE_KEY  CreateListReplyStatusT = 1
	CreateListReply_INTERNAL_ERROR CreateListReplyStatusT = 2
)

// Enum value maps for CreateListReplyStatusT.
var (
	CreateListReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "DUPLICATE_KEY",
		2: "INTERNAL_ERROR",
	}
	CreateListReplyStatusT_value = map[string]int32{
		"OK":             0,
		"DUPLICATE_KEY":  1,
		"INTERNAL_ERROR": 2,
	}
)

func (x CreateListReplyStatusT) Enum() *CreateListReplyStatusT {
	p := new(CreateListReplyStatusT)
	*p = x
	return p
}

func (x CreateListReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateListReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[1].Descriptor()
}

func (CreateListReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[1]
}

func (x CreateListReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateListReplyStatusT.Descriptor instead.
func (CreateListReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{3, 0}
}

type DeleteListReplyStatusT int32

const (
	DeleteListReply_OK             DeleteListReplyStatusT = 0
	DeleteListReply_NOT_FOUND      DeleteListReplyStatusT = 1
	DeleteListReply_INTERNAL_ERROR DeleteListReplyStatusT = 2
)

// Enum value maps for DeleteListReplyStatusT.
var (
	DeleteListReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "INTERNAL_ERROR",
	}
	DeleteListReplyStatusT_value = map[string]int32{
		"OK":             0,
		"NOT_FOUND":      1,
		"INTERNAL_ERROR": 2,
	}
)

func (x DeleteListReplyStatusT) Enum() *DeleteListReplyStatusT {
	p := new(DeleteListReplyStatusT)
	*p = x
	return p
}

func (x DeleteListReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteListReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[2].Descriptor()
}

func (DeleteListReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[2]
}

func (x DeleteListReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteListReplyStatusT.Descriptor instead.
func (DeleteListReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{5, 0}
}

type SetListReplyStatusT int32

const (
	SetListReply_OK             SetListReplyStatusT = 0
	SetListReply_INTERNAL_ERROR SetListReplyStatusT = 1
)

// Enum value maps for SetListReplyStatusT.
var (
	SetListReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "INTERNAL_ERROR",
	}
	SetListReplyStatusT_value = map[string]int32{
		"OK":             0,
		"INTERNAL_ERROR": 1,
	}
)

func (x SetListReplyStatusT) Enum() *SetListReplyStatusT {
	p := new(SetListReplyStatusT)
	*p = x
	return p
}

func (x SetListReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetListReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[3].Descriptor()
}

func (SetListReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[3]
}

func (x SetListReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetListReplyStatusT.Descriptor instead.
func (SetListReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{8, 0}
}

type SetListVersionReplyStatusT int32

const (
	SetListVersionReply_OK             SetListVersionReplyStatusT = 0
	SetListVersionReply_NOT_FOUND      SetListVersionReplyStatusT = 1
	SetListVersionReply_INTERNAL_ERROR SetListVersionReplyStatusT = 2
)

// Enum value maps for SetListVersionReplyStatusT.
var (
	SetListVersionReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "INTERNAL_ERROR",
	}
	SetListVersionReplyStatusT_value = map[string]int32{
		"OK":             0,
		"NOT_FOUND":      1,
		"INTERNAL_ERROR": 2,
	}
)

func (x SetListVersionReplyStatusT) Enum() *SetListVersionReplyStatusT {
	p := new(SetListVersionReplyStatusT)
	*p = x
	return p
}

func (x SetListVersionReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetListVersionReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[4].Descriptor()
}

func (SetListVersionReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[4]
}

func (x SetListVersionReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetListVersionReplyStatusT.Descriptor instead.
func (SetListVersionReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{10, 0}
}

type DeleteListNodeBeforeReplyStatusT int32

const (
	DeleteListNodeBeforeReply_OK             DeleteListNodeBeforeReplyStatusT = 0
	DeleteListNodeBeforeReply_INTERNAL_ERROR DeleteListNodeBeforeReplyStatusT = 1
)

// Enum value maps for DeleteListNodeBeforeReplyStatusT.
var (
	DeleteListNodeBeforeReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "INTERNAL_ERROR",
	}
	DeleteListNodeBeforeReplyStatusT_value = map[string]int32{
		"OK":             0,
		"INTERNAL_ERROR": 1,
	}
)

func (x DeleteListNodeBeforeReplyStatusT) Enum() *DeleteListNodeBeforeReplyStatusT {
	p := new(DeleteListNodeBeforeReplyStatusT)
	*p = x
	return p
}

func (x DeleteListNodeBeforeReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteListNodeBeforeReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[5].Descriptor()
}

func (DeleteListNodeBeforeReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[5]
}

func (x DeleteListNodeBeforeReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteListNodeBeforeReplyStatusT.Descriptor instead.
func (DeleteListNodeBeforeReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{12, 0}
}

type HeadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HeadRequest) Reset() {
	*x = HeadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadRequest) ProtoMessage() {}

func (x *HeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadRequest.ProtoReflect.Descriptor instead.
func (*HeadRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{0}
}

func (x *HeadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HeadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status HeadReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.HeadReplyStatusT" json:"status,omitempty"`
	ListId uint32           `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *HeadReply) Reset() {
	*x = HeadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadReply) ProtoMessage() {}

func (x *HeadReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadReply.ProtoReflect.Descriptor instead.
func (*HeadReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{1}
}

func (x *HeadReply) GetStatus() HeadReplyStatusT {
	if x != nil {
		return x.Status
	}
	return HeadReply_OK
}

func (x *HeadReply) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

type CreateListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListKey string `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
}

func (x *CreateListRequest) Reset() {
	*x = CreateListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListRequest) ProtoMessage() {}

func (x *CreateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListRequest.ProtoReflect.Descriptor instead.
func (*CreateListRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{2}
}

func (x *CreateListRequest) GetListKey() string {
	if x != nil {
		return x.ListKey
	}
	return ""
}

type CreateListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status CreateListReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.CreateListReplyStatusT" json:"status,omitempty"`
	ListId uint32                 `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *CreateListReply) Reset() {
	*x = CreateListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListReply) ProtoMessage() {}

func (x *CreateListReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListReply.ProtoReflect.Descriptor instead.
func (*CreateListReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{3}
}

func (x *CreateListReply) GetStatus() CreateListReplyStatusT {
	if x != nil {
		return x.Status
	}
	return CreateListReply_OK
}

func (x *CreateListReply) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

type DeleteListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId uint32 `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *DeleteListRequest) Reset() {
	*x = DeleteListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListRequest) ProtoMessage() {}

func (x *DeleteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListRequest.ProtoReflect.Descriptor instead.
func (*DeleteListRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteListRequest) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

type DeleteListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DeleteListReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.DeleteListReplyStatusT" json:"status,omitempty"`
	ListId uint32                 `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *DeleteListReply) Reset() {
	*x = DeleteListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListReply) ProtoMessage() {}

func (x *DeleteListReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListReply.ProtoReflect.Descriptor instead.
func (*DeleteListReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteListReply) GetStatus() DeleteListReplyStatusT {
	if x != nil {
		return x.Status
	}
	return DeleteListReply_OK
}

func (x *DeleteListReply) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

type SetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId  uint32  `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Version uint32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Nodes   []*Node `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *SetListRequest) Reset() {
	*x = SetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListRequest) ProtoMessage() {}

func (x *SetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListRequest.ProtoReflect.Descriptor instead.
func (*SetListRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{6}
}

func (x *SetListRequest) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

func (x *SetListRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SetListRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order     uint32 `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	ArticleId uint32 `protobuf:"varint,4,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{7}
}

func (x *Node) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Node) GetArticleId() uint32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type SetListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SetListReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.SetListReplyStatusT" json:"status,omitempty"`
}

func (x *SetListReply) Reset() {
	*x = SetListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListReply) ProtoMessage() {}

func (x *SetListReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListReply.ProtoReflect.Descriptor instead.
func (*SetListReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{8}
}

func (x *SetListReply) GetStatus() SetListReplyStatusT {
	if x != nil {
		return x.Status
	}
	return SetListReply_OK
}

type SetListVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId  uint32 `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SetListVersionRequest) Reset() {
	*x = SetListVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListVersionRequest) ProtoMessage() {}

func (x *SetListVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListVersionRequest.ProtoReflect.Descriptor instead.
func (*SetListVersionRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{9}
}

func (x *SetListVersionRequest) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

func (x *SetListVersionRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SetListVersionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SetListVersionReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.SetListVersionReplyStatusT" json:"status,omitempty"`
}

func (x *SetListVersionReply) Reset() {
	*x = SetListVersionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListVersionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListVersionReply) ProtoMessage() {}

func (x *SetListVersionReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListVersionReply.ProtoReflect.Descriptor instead.
func (*SetListVersionReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{10}
}

func (x *SetListVersionReply) GetStatus() SetListVersionReplyStatusT {
	if x != nil {
		return x.Status
	}
	return SetListVersionReply_OK
}

type DeleteListNodeBeforeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Before *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
}

func (x *DeleteListNodeBeforeRequest) Reset() {
	*x = DeleteListNodeBeforeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteListNodeBeforeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListNodeBeforeRequest) ProtoMessage() {}

func (x *DeleteListNodeBeforeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListNodeBeforeRequest.ProtoReflect.Descriptor instead.
func (*DeleteListNodeBeforeRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteListNodeBeforeRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type DeleteListNodeBeforeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DeleteListNodeBeforeReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.DeleteListNodeBeforeReplyStatusT" json:"status,omitempty"`
}

func (x *DeleteListNodeBeforeReply) Reset() {
	*x = DeleteListNodeBeforeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteListNodeBeforeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListNodeBeforeReply) ProtoMessage() {}

func (x *DeleteListNodeBeforeReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListNodeBeforeReply.ProtoReflect.Descriptor instead.
func (*DeleteListNodeBeforeReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteListNodeBeforeReply) GetStatus() DeleteListNodeBeforeReplyStatusT {
	if x != nil {
		return x.Status
	}
	return DeleteListNodeBeforeReply_OK
}

var File_controller_pb_model_proto protoreflect.FileDescriptor

var file_controller_pb_model_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1f, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x89, 0x01, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x2e, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x99, 0x01,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22,
	0x38, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x5f,
	0x4b, 0x45, 0x59, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x07, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22,
	0x63, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0x67, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e,
	0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x4a, 0x0a, 0x15, 0x53, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x51, 0x0a,
	0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x42,
	0x65, 0x66, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06,
	0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65,
	0x22, 0x81, 0x01, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3d,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x54, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x32, 0x88, 0x03, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x46, 0x0a,
	0x0e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1f, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x64,
	0x65, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61,
	0x79, 0x31, 0x34, 0x32, 0x32, 0x2f, 0x64, 0x63, 0x61, 0x72, 0x64, 0x2d, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2d, 0x32, 0x30, 0x32, 0x33, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controller_pb_model_proto_rawDescOnce sync.Once
	file_controller_pb_model_proto_rawDescData = file_controller_pb_model_proto_rawDesc
)

func file_controller_pb_model_proto_rawDescGZIP() []byte {
	file_controller_pb_model_proto_rawDescOnce.Do(func() {
		file_controller_pb_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_controller_pb_model_proto_rawDescData)
	})
	return file_controller_pb_model_proto_rawDescData
}

var file_controller_pb_model_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_controller_pb_model_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_controller_pb_model_proto_goTypes = []interface{}{
	(HeadReplyStatusT)(0),                 // 0: pb.HeadReply.statusT
	(CreateListReplyStatusT)(0),           // 1: pb.CreateListReply.statusT
	(DeleteListReplyStatusT)(0),           // 2: pb.DeleteListReply.statusT
	(SetListReplyStatusT)(0),              // 3: pb.SetListReply.statusT
	(SetListVersionReplyStatusT)(0),       // 4: pb.SetListVersionReply.statusT
	(DeleteListNodeBeforeReplyStatusT)(0), // 5: pb.DeleteListNodeBeforeReply.statusT
	(*HeadRequest)(nil),                   // 6: pb.HeadRequest
	(*HeadReply)(nil),                     // 7: pb.HeadReply
	(*CreateListRequest)(nil),             // 8: pb.CreateListRequest
	(*CreateListReply)(nil),               // 9: pb.CreateListReply
	(*DeleteListRequest)(nil),             // 10: pb.DeleteListRequest
	(*DeleteListReply)(nil),               // 11: pb.DeleteListReply
	(*SetListRequest)(nil),                // 12: pb.SetListRequest
	(*Node)(nil),                          // 13: pb.Node
	(*SetListReply)(nil),                  // 14: pb.SetListReply
	(*SetListVersionRequest)(nil),         // 15: pb.SetListVersionRequest
	(*SetListVersionReply)(nil),           // 16: pb.SetListVersionReply
	(*DeleteListNodeBeforeRequest)(nil),   // 17: pb.DeleteListNodeBeforeRequest
	(*DeleteListNodeBeforeReply)(nil),     // 18: pb.DeleteListNodeBeforeReply
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
}
var file_controller_pb_model_proto_depIdxs = []int32{
	0,  // 0: pb.HeadReply.status:type_name -> pb.HeadReply.statusT
	1,  // 1: pb.CreateListReply.status:type_name -> pb.CreateListReply.statusT
	2,  // 2: pb.DeleteListReply.status:type_name -> pb.DeleteListReply.statusT
	13, // 3: pb.SetListRequest.nodes:type_name -> pb.Node
	3,  // 4: pb.SetListReply.status:type_name -> pb.SetListReply.statusT
	4,  // 5: pb.SetListVersionReply.status:type_name -> pb.SetListVersionReply.statusT
	19, // 6: pb.DeleteListNodeBeforeRequest.before:type_name -> google.protobuf.Timestamp
	5,  // 7: pb.DeleteListNodeBeforeReply.status:type_name -> pb.DeleteListNodeBeforeReply.statusT
	6,  // 8: pb.ListService.Head:input_type -> pb.HeadRequest
	10, // 9: pb.ListService.DeleteList:input_type -> pb.DeleteListRequest
	8,  // 10: pb.ListService.CreateList:input_type -> pb.CreateListRequest
	12, // 11: pb.ListService.SetList:input_type -> pb.SetListRequest
	15, // 12: pb.ListService.SetListVersion:input_type -> pb.SetListVersionRequest
	17, // 13: pb.ListService.DeleteListNodeBefore:input_type -> pb.DeleteListNodeBeforeRequest
	7,  // 14: pb.ListService.Head:output_type -> pb.HeadReply
	11, // 15: pb.ListService.DeleteList:output_type -> pb.DeleteListReply
	9,  // 16: pb.ListService.CreateList:output_type -> pb.CreateListReply
	14, // 17: pb.ListService.SetList:output_type -> pb.SetListReply
	16, // 18: pb.ListService.SetListVersion:output_type -> pb.SetListVersionReply
	18, // 19: pb.ListService.DeleteListNodeBefore:output_type -> pb.DeleteListNodeBeforeReply
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_controller_pb_model_proto_init() }
func file_controller_pb_model_proto_init() {
	if File_controller_pb_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controller_pb_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListVersionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteListNodeBeforeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteListNodeBeforeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controller_pb_model_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_pb_model_proto_goTypes,
		DependencyIndexes: file_controller_pb_model_proto_depIdxs,
		EnumInfos:         file_controller_pb_model_proto_enumTypes,
		MessageInfos:      file_controller_pb_model_proto_msgTypes,
	}.Build()
	File_controller_pb_model_proto = out.File
	file_controller_pb_model_proto_rawDesc = nil
	file_controller_pb_model_proto_goTypes = nil
	file_controller_pb_model_proto_depIdxs = nil
}
