// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: controller/pb/model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateListReplyStatusT int32

const (
	CreateListReply_OK             CreateListReplyStatusT = 0
	CreateListReply_DUPLICATED_KEY CreateListReplyStatusT = 1
	CreateListReply_INTERNAL_ERROR CreateListReplyStatusT = 2
)

// Enum value maps for CreateListReplyStatusT.
var (
	CreateListReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "DUPLICATED_KEY",
		2: "INTERNAL_ERROR",
	}
	CreateListReplyStatusT_value = map[string]int32{
		"OK":             0,
		"DUPLICATED_KEY": 1,
		"INTERNAL_ERROR": 2,
	}
)

func (x CreateListReplyStatusT) Enum() *CreateListReplyStatusT {
	p := new(CreateListReplyStatusT)
	*p = x
	return p
}

func (x CreateListReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateListReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[0].Descriptor()
}

func (CreateListReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[0]
}

func (x CreateListReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateListReplyStatusT.Descriptor instead.
func (CreateListReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{1, 0}
}

type SetListReplyStatusT int32

const (
	SetListReply_OK             SetListReplyStatusT = 0
	SetListReply_INTERNAL_ERROR SetListReplyStatusT = 1
)

// Enum value maps for SetListReplyStatusT.
var (
	SetListReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "INTERNAL_ERROR",
	}
	SetListReplyStatusT_value = map[string]int32{
		"OK":             0,
		"INTERNAL_ERROR": 1,
	}
)

func (x SetListReplyStatusT) Enum() *SetListReplyStatusT {
	p := new(SetListReplyStatusT)
	*p = x
	return p
}

func (x SetListReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetListReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[1].Descriptor()
}

func (SetListReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[1]
}

func (x SetListReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetListReplyStatusT.Descriptor instead.
func (SetListReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{4, 0}
}

type SetListVersionReplyStatusT int32

const (
	SetListVersionReply_OK             SetListVersionReplyStatusT = 0
	SetListVersionReply_NOT_FOUND      SetListVersionReplyStatusT = 1
	SetListVersionReply_INTERNAL_ERROR SetListVersionReplyStatusT = 2
)

// Enum value maps for SetListVersionReplyStatusT.
var (
	SetListVersionReplyStatusT_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "INTERNAL_ERROR",
	}
	SetListVersionReplyStatusT_value = map[string]int32{
		"OK":             0,
		"NOT_FOUND":      1,
		"INTERNAL_ERROR": 2,
	}
)

func (x SetListVersionReplyStatusT) Enum() *SetListVersionReplyStatusT {
	p := new(SetListVersionReplyStatusT)
	*p = x
	return p
}

func (x SetListVersionReplyStatusT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetListVersionReplyStatusT) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_pb_model_proto_enumTypes[2].Descriptor()
}

func (SetListVersionReplyStatusT) Type() protoreflect.EnumType {
	return &file_controller_pb_model_proto_enumTypes[2]
}

func (x SetListVersionReplyStatusT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetListVersionReplyStatusT.Descriptor instead.
func (SetListVersionReplyStatusT) EnumDescriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{6, 0}
}

type CreateListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListName string `protobuf:"bytes,1,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`
}

func (x *CreateListRequest) Reset() {
	*x = CreateListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListRequest) ProtoMessage() {}

func (x *CreateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListRequest.ProtoReflect.Descriptor instead.
func (*CreateListRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListRequest) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

type CreateListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status CreateListReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.CreateListReplyStatusT" json:"status,omitempty"`
}

func (x *CreateListReply) Reset() {
	*x = CreateListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListReply) ProtoMessage() {}

func (x *CreateListReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListReply.ProtoReflect.Descriptor instead.
func (*CreateListReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{1}
}

func (x *CreateListReply) GetStatus() CreateListReplyStatusT {
	if x != nil {
		return x.Status
	}
	return CreateListReply_OK
}

type SetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId  uint32  `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Version uint32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Nodes   []*Node `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *SetListRequest) Reset() {
	*x = SetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListRequest) ProtoMessage() {}

func (x *SetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListRequest.ProtoReflect.Descriptor instead.
func (*SetListRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{2}
}

func (x *SetListRequest) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

func (x *SetListRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SetListRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order     uint32 `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	ArticleId uint32 `protobuf:"varint,4,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Node) GetArticleId() uint32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type SetListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SetListReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.SetListReplyStatusT" json:"status,omitempty"`
}

func (x *SetListReply) Reset() {
	*x = SetListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListReply) ProtoMessage() {}

func (x *SetListReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListReply.ProtoReflect.Descriptor instead.
func (*SetListReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{4}
}

func (x *SetListReply) GetStatus() SetListReplyStatusT {
	if x != nil {
		return x.Status
	}
	return SetListReply_OK
}

type SetListVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId  uint32 `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SetListVersionRequest) Reset() {
	*x = SetListVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListVersionRequest) ProtoMessage() {}

func (x *SetListVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListVersionRequest.ProtoReflect.Descriptor instead.
func (*SetListVersionRequest) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{5}
}

func (x *SetListVersionRequest) GetListId() uint32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

func (x *SetListVersionRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SetListVersionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SetListVersionReplyStatusT `protobuf:"varint,1,opt,name=status,proto3,enum=pb.SetListVersionReplyStatusT" json:"status,omitempty"`
}

func (x *SetListVersionReply) Reset() {
	*x = SetListVersionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_pb_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetListVersionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListVersionReply) ProtoMessage() {}

func (x *SetListVersionReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_pb_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListVersionReply.ProtoReflect.Descriptor instead.
func (*SetListVersionReply) Descriptor() ([]byte, []int) {
	return file_controller_pb_model_proto_rawDescGZIP(), []int{6}
}

func (x *SetListVersionReply) GetStatus() SetListVersionReplyStatusT {
	if x != nil {
		return x.Status
	}
	return SetListVersionReply_OK
}

var File_controller_pb_model_proto protoreflect.FileDescriptor

var file_controller_pb_model_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x30, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x54, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x39, 0x0a, 0x07, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x4b, 0x45, 0x59, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x63, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x04, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x54, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x07, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e,
	0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x22, 0x4a, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x84, 0x01, 0x0a,
	0x13, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x54, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x32, 0xc8, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x35, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x35,
	0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x79,
	0x31, 0x34, 0x32, 0x32, 0x2f, 0x64, 0x63, 0x61, 0x72, 0x64, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2d, 0x32, 0x30, 0x32, 0x33, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controller_pb_model_proto_rawDescOnce sync.Once
	file_controller_pb_model_proto_rawDescData = file_controller_pb_model_proto_rawDesc
)

func file_controller_pb_model_proto_rawDescGZIP() []byte {
	file_controller_pb_model_proto_rawDescOnce.Do(func() {
		file_controller_pb_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_controller_pb_model_proto_rawDescData)
	})
	return file_controller_pb_model_proto_rawDescData
}

var file_controller_pb_model_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_controller_pb_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_controller_pb_model_proto_goTypes = []interface{}{
	(CreateListReplyStatusT)(0),     // 0: pb.CreateListReply.statusT
	(SetListReplyStatusT)(0),        // 1: pb.SetListReply.statusT
	(SetListVersionReplyStatusT)(0), // 2: pb.SetListVersionReply.statusT
	(*CreateListRequest)(nil),       // 3: pb.CreateListRequest
	(*CreateListReply)(nil),         // 4: pb.CreateListReply
	(*SetListRequest)(nil),          // 5: pb.SetListRequest
	(*Node)(nil),                    // 6: pb.Node
	(*SetListReply)(nil),            // 7: pb.SetListReply
	(*SetListVersionRequest)(nil),   // 8: pb.SetListVersionRequest
	(*SetListVersionReply)(nil),     // 9: pb.SetListVersionReply
}
var file_controller_pb_model_proto_depIdxs = []int32{
	0, // 0: pb.CreateListReply.status:type_name -> pb.CreateListReply.statusT
	6, // 1: pb.SetListRequest.nodes:type_name -> pb.Node
	1, // 2: pb.SetListReply.status:type_name -> pb.SetListReply.statusT
	2, // 3: pb.SetListVersionReply.status:type_name -> pb.SetListVersionReply.statusT
	3, // 4: pb.ListService.CreateList:input_type -> pb.CreateListRequest
	5, // 5: pb.ListService.SetList:input_type -> pb.SetListRequest
	8, // 6: pb.ListService.SetListVersion:input_type -> pb.SetListVersionRequest
	4, // 7: pb.ListService.CreateList:output_type -> pb.CreateListReply
	7, // 8: pb.ListService.SetList:output_type -> pb.SetListReply
	9, // 9: pb.ListService.SetListVersion:output_type -> pb.SetListVersionReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_controller_pb_model_proto_init() }
func file_controller_pb_model_proto_init() {
	if File_controller_pb_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controller_pb_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_pb_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetListVersionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controller_pb_model_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_pb_model_proto_goTypes,
		DependencyIndexes: file_controller_pb_model_proto_depIdxs,
		EnumInfos:         file_controller_pb_model_proto_enumTypes,
		MessageInfos:      file_controller_pb_model_proto_msgTypes,
	}.Build()
	File_controller_pb_model_proto = out.File
	file_controller_pb_model_proto_rawDesc = nil
	file_controller_pb_model_proto_goTypes = nil
	file_controller_pb_model_proto_depIdxs = nil
}
